soc: qcom: event_timer: Fix compilation breakage from 4.14.250
Upstream commit 0135fcb86a0bc9e4484f7e1228cadcc343c5edef ("lib/timerqueue: Rely on rbtree semantics for next timer") changed the timerque struct.

drivers/soc/qcom/event_timer.c:54:3: error: field designator 'head' does not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'struct timerqueue_head')
        .head = RB_ROOT,
         ^
drivers/soc/qcom/event_timer.c:55:3: error: field designator 'next' does not refer to any field in type 'typeof(struct timerqueue_head)' (aka 'struct timerqueue_head')
        .next = NULL,
         ^
2 errors generated.

Signed-off-by: atndko <z1281552865@gmail.com>
Change-Id: I6cdd2c599ad33357feb4c557f15f3df0f4a34a05